### ISSUE TITLE
Feature request: adding information to json

### ISSUE THREAD

**Issue by treanus** [cbedetti/Dcm2Bids#22]
I would like to propose an enhancement: the possibility to add fields with information to the bids json files.

In some cases dcm2niix cannot set all bids fields in the json file, since the info is not available in the dicom headers. One example is the "TaskName" field in (resting state) fMRI. Another may be the "SliceTiming" information, not provided in e.g. Philips dicom. 

This information could be provided in the config_dcm2bids.json, e.g.:

{
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-rest",
            "criteria": {
                "SeriesDescription": "fMRI_resting*"
            }
           "customField": {
                 "TaskName": "rest"
                 "SliceTimimg": [0 0.7 1.4 etc...]
            }
}

Another example could be:

{
            "dataType": "fmap",
	    "modalityLabel": "fieldmap",
            "criteria": {
                "SeriesDescription": "B0_map",
                "ScanningSequence": "RM"          
			}
             "customField": {
                 "Units": "Hz"
                 "IntendFor": "ses-pos2/func/sub-001_ses-pos2_task-rest_bold.nii.gz"
              }
}

The "customField" thus contains information to be added in the json, specific for each dicom acquisition. Of course, since the info is not in the dicom, the user is responsible for providing the correct information.

Hope to hear your feedback on this idea.

Best regards,
Stefan.

**Comment by jooh** [comment]
You may wish to check out my fork of dcm2bids, which has this feature.

https://github.com/jooh/Dcm2Bids

A PR to merge in this feature was rejected. I don't have time to negotiate
further (my fork already does what I need it to do so that's the version
we're using in production at MRC CBU), but if someone else wants to fork me
and make whatever changes the maintainer requires it might be possible to
get the feature into the main repo that way.

https://github.com/cbedetti/Dcm2Bids/commit/a1610c5b724683fa97fef856c582434ea9a65365

I agree that's it's an important feature so we don't depend on dcm2niix
being infallible.  There will always be edge cases that require manual
intervention.

Johan


On 9 Feb 2018 08:32, "treanus" <notifications@github.com> wrote:

I would like to propose an enhancement: the possibility to add fields with
information to the bids json files.

In some cases dcm2niix cannot set all bids fields in the json file, since
the info is not available in the dicom headers. One example is the
"TaskName" field in (resting state) fMRI. Another may be the "SliceTiming"
information, not provided in e.g. Philips dicom.

This information could be provided in the config_dcm2bids.json, e.g.:

{
"dataType": "func",
"modalityLabel": "bold",
"customLabels": "task-rest",
"criteria": {
"SeriesDescription": "fMRI_resting*"
}
"customField": {
"TaskName": "rest"
"SliceTimimg": [0 0.7 1.4 etc...]
}
}

Another example could be:

{
"dataType": "fmap",
"modalityLabel": "fieldmap",
"criteria": {
"SeriesDescription": "B0_map",
"ScanningSequence": "RM"
}
"customField": {
"Units": "Hz"
"IntendFor": "ses-pos2/func/sub-001_ses-pos2_task-rest_bold.nii.gz"
}
}

The "customField" thus contains information to be added in the json,
specific for each dicom acquisition. Of course, since the info is not in
the dicom, the user is responsible for providing the correct information.

Hope to hear your feedback on this idea.

Best regards,
Stefan.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cbedetti/Dcm2Bids/issues/22>, or mute the thread

**Comment by treanus** [comment]
Thank you Johan,
this works for me.
I agree that this may be useful for the main fork.

Best regards,

Stefan.

**Comment by gladomat** [comment]
At least adding the `"TaskName": "rest"`should be implemented, otherwise the BIDS validator linked on the site doesn't validate the functional data, which then needs to be added manually for each run.

**Comment by cbedetti** [comment]
> At least adding the `"TaskName": "rest"`should be implemented, otherwise the BIDS validator linked on the site doesn't validate the functional data, which then needs to be added manually for each run.

This is already the case with the `customLabels`
`"customLabels": "task-rest"`

**Comment by cbedetti** [comment]
Thank you for reporting this issue @treanus 
This is now possible with the `sidecarChanges` option.

Thank for your reply @jooh and for providing a solution.
Since I refactored most of the code I could not implement your code for this solution.
