### ISSUE TITLE
Match on lists

### ISSUE THREAD

**Issue by rhancockn** [cbedetti/Dcm2Bids#30]
It would be helpful to match on list elements. For example, acquisitions may undergo different filtering/reconstruction options that are differentiated only in the "ImageType" elements, e.g.
`"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND", "NORM"],`
`"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND"],`

Adding `"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND", "NORM"]`
 `criteria` has no effect-the two reconstructions appear as separate runs.

**Comment by dasturge** [comment]
I just discovered that this behavior is actually just not what you expect.  It matches *any* elements of the list instead of *all* elements of the list...

e.g., 
"ImageType": ["NORM"]

will only match the prescan normalized image.  This behavior should probably be corrected, as it only allows you to isolate the prescan normalized image.

**Comment by cbedetti** [comment]
That was a bug in the design searching through criteria.
The version 2.0.0 works the way you describe here.
Thanks
